version: '3'

services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: 'my_project_db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'changeme'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
